### ISSUE TITLE
bamboofox little-asm-impossible 問題詢問

### ISSUE THREAD

**Issue by swt02026** [L4ys/CTF#1]
不好意思

我在看你的writeup

發現到我同樣用ida產出c

可是你的writeup裡面

有把

`dword_2020D8 += a1 << 113 * a1 + ....`

注解

我用ida產出的code改好用klee跑 跑不出東西

把那幾行code註解後就跑得出來

請問那幾行註解後的差異是什麼呢？

謝謝

**Comment by L4ys** [comment]
那幾行運算不會影響結果，但是會造成 overshift error
可以在 klee 的參數加上`-check-overshift=0` 或是直接用 [LazyKLEE](https://github.com/L4ys/LazyKLEE)
